### ISSUE TITLE
Using roxygen2 to generate NAMESPACE

### ISSUE THREAD

**Issue by jonocarroll** [coolbutuseless/simplercpp#2]
Not a bug, but perhaps helpful notes based on a slight variation I worked with... not worth a blog post of my own, but may be of value to someone.

I *finally* got my own version working with some external C code I've been wrestling with for a while now, but couldn't call the functions externally. It turns out it was because I was using `roxygen2` to build `NAMESPACE`, so the pieces I was missing were:
```r
#' @useDynLib pkgname
#' @importFrom Rcpp sourceCpp
"_PACKAGE"
```
in e.g. `pkgname-package.R`, and including both of
```r
//' @export
// [[Rcpp::export]]
```
in the `.cpp` source.

I eventually found both of these [here](http://r-pkgs.had.co.nz/src.html#cpp) and I clearly skipped over those when I originally read the book as I had 0 knowledge of `Rcpp` at the time.

The advice I've seen around to use `exportPattern("^[[:alpha:]]+")` fails when using `roxygen2` as you either can't edit `NAMESPACE` manually, or are stuck with *just* those lines (no using `roxygen2` to populate).

Of course, I'm happy to be shown where I've gone wrong.

**Comment by coolbutuseless** [comment]
Thanks @jonocarroll   - i tweaked the package a bit to use roxygen2.
